//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVData.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=\"I:\\DATA_Programovani\\Visual Studio 2012\\Projects\\DVData\\DVData\\bin\\D" +
            "ebug\\Films.mdf\";useutf16encoding=True")]
        public string FCS_SQLite {
            get {
                return ((string)(this["FCS_SQLite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("useutf16encoding=True;data source=\"I:\\DATA_Programovani\\Visual Studio 2012\\Projec" +
            "ts\\DVData\\DVData\\bin\\Debug\\Films.mdf\"")]
        public string FCS_SQLite_TA {
            get {
                return ((string)(this["FCS_SQLite_TA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("useutf16encoding=True;data source=\"I:\\DATA_Programovani\\Visual Studio 2012\\Projec" +
            "ts\\DVData\\DVData\\bin\\Debug\\Films.db\"")]
        public string FCS_SQLite_dbf {
            get {
                return ((string)(this["FCS_SQLite_dbf"]));
            }
        }
    }
}
